### ISSUE TITLE
Better UI

### ISSUE THREAD

**Issue by harshu0001** [mohitahlawat2001/MathematicsSwitchApp#17]
Please ensure a better UI for the webpage to make it look nicer. Adding a better background, buttons, hover effects, etc. can be applied to make it look more impressive. 
Please consider these points.
Thank You!

**Comment by Upendra2003** [comment]
Hey @harshu0001 can you assign me this I can make the UI better.

**Comment by Prakharpandey007** [comment]
Hii,please accept my pull request.
