### ISSUE TITLE
Add Commas automatically on space and remove alphabet if typed

### ISSUE THREAD

**Issue by shauryakushwaha08** [mohitahlawat2001/MathematicsSwitchApp#31]
When the user presses the space the commas will added for an easier user experience(UX).
If any alphabet or character other than commas is typed it will be removed and a message will be shown to provide input in the correct format.

**Comment by shauryakushwaha08** [comment]
Why did you do it invalid?

**Comment by mohitahlawat2001** [comment]
not needed
