### ISSUE TITLE
add js code to make the function work more smoothly as well as make it faster

### ISSUE THREAD

**Issue by rohitagr0310** [mohitahlawat2001/MathematicsSwitchApp#7]

**Comment by mohitahlawat2001** [comment]
added photo before and after change!

**Comment by rohitagr0310** [comment]
i have completed my task and have pushed the code. please review the pr

**Comment by rohitagr0310** [comment]
Before - 
![image](https://github.com/mohitahlawat2001/MathematicsSwitchApp/assets/110839621/8e29de73-a8d5-4d82-853b-7217563c41f6)

After - 
![image](https://github.com/mohitahlawat2001/MathematicsSwitchApp/assets/110839621/0c61a88c-6ddf-48fe-979a-3932e275a70c)
